[run]
init_cmds = [
	["make", "build-dev"],
	["./myapp", "web"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/cmd",
	"$WORKDIR/routers",
    "$WORKDIR/context",
    "$WORKDIR/stuff",
    "$WORKDIR/models",
    "$WORKDIR/conf/locale",
]
watch_exts = [".go"]
ignore_files = [".+_test.go"]
build_delay = 1500
cmds = [
	["make", "build-dev"], # TAGS=sqlite cert pam tidb
	["./myapp", "web"]
]
