workspace:
  base: /srv/app
  path: src/dev.sigpipe.me/dashie/reel2bits

pipeline:
  clone:
    image: plugins/git
    depth: 50
    tags: true

  build:
    image: webhippie/golang:edge
    pull: true
    environment:
      TAGS: sqlite
      GOPATH: /srv/app
    commands:
      - apk -U add sox sox-dev taglib taglib-dev libmagic file-dev
      - go get github.com/Masterminds/glide
      - glide install
      - make clean
      - make vet
      - make lint
      - make misspell-check
      - make build
    when:
      event: [ push, tag, pull_request ]

  test:
    image: webhippie/golang:edge
    pull: true
    environment:
      TAGS: sqlite
      GOPATH: /srv/app
    commands:
      - apk -U add sox sox-dev taglib taglib-dev libmagic file-dev
      - make test
    when:
      event: [ tag, pull_request ]

  test-sqlite:
    image: webhippie/golang:edge
    pull: true
    environment:
      GOPATH: /srv/app
    commands:
      - apk -U add sox sox-dev taglib taglib-dev libmagic file-dev
      - make test-sqlite
    when:
      event: [ push, tag, pull_request ]

#  static:
#    image: karalabe/xgo-latest:latest
#    pull: true
#    environment:
#      TAGS: sqlite
#      GOPATH: /srv/app
#    commands:
#      - apk -U add sox sox-dev taglib taglib-dev libmagic file-dev
#      - make release
#    when:
#      event: [ push, tag ]

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: gitea
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure ]
