clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

pipeline:
  restore-cache:
      image: drillster/drone-volume-cache
      restore: true
      mount:
          - .cache
      volumes:
          - /tmp/cache:/cache

  build:
    image: python:3-alpine
    commands:
      - apk -U add sox sox-dev taglib taglib-dev libmagic file-dev libffi libffi-dev
      - apk add cmake gcc g++ make pkgconfig git boost-dev gd-dev libmad-dev libsndfile-dev libid3tag-dev wget postgresql-dev
      - pip install --upgrade pip setuptools
      - pip install --cache-dir=/cache flake8
      - pip install --cache-dir=/cache black
      - pip install --cache-dir=/cache -r requirements.txt
      - python setup.py install
      - ./tests/install_audiowaveform.sh
      - black --check .
      - flake8 .
      - python setup.py test

  migrations:
    image: python:3-alpine
    commands:
      - apk -U add sox sox-dev taglib taglib-dev libmagic file-dev libffi libffi-dev postgresql-client
      - apk add cmake gcc g++ make pkgconfig git boost-dev gd-dev libmad-dev libsndfile-dev libid3tag-dev wget postgresql-dev
      - pip install --upgrade pip setuptools
      - pip install --cache-dir=/cache flake8
      - pip install --cache-dir=/cache black
      - pip install --cache-dir=/cache -r requirements.txt
      - python setup.py install
      - psql -U postgres -h database -w -c 'CREATE DATABASE reel2bits'
      - psql -U postgres -h database -w -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' reel2bits
      - cp config.py.sample config.py
      - flask db upgrade

  rebuild-cache:
      image: drillster/drone-volume-cache
      rebuild: true
      mount:
          - .cache
      volumes:
          - /tmp/cache:/cache

  publish-web:
    image: plugins/docker
    repo: dashie/reel2bits-web
    dockerfile: Dockerfile-web
    tags: [ latest ]
    secrets:
        - DOCKER_USERNAME
        - DOCKER_PASSWORD

  publish-worker:
    image: plugins/docker
    repo: dashie/reel2bits-worker
    dockerfile: Dockerfile-worker
    tags: [ latest ]
    secrets:
        - DOCKER_USERNAME
        - DOCKER_PASSWORD

  notify:
    image: plugins/slack
    channel: gitea
    secrets:
      - SLACK_WEBHOOK
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure, success ]

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=reel2bits_test
