clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

pipeline:
  ping:
    image: postgres
    commands:
      # wait for postgres service to become available
      - |
        until psql -U postgres -d reel2bits_test -h postgres \
         -c "SELECT 1;" >/dev/null 2>&1; do sleep 1; done
      # query the database
      - |
        psql -U postgres -d reel2bits_test -h database \
        -c "SELECT * FROM pg_catalog.pg_tables;"

  restore-cache:
      image: drillster/drone-volume-cache
      restore: true
      mount:
          - .cache
      volumes:
          - /tmp/cache:/cache

  build:
    image: python:3-alpine
    commands:
      - apk -U add sox sox-dev taglib taglib-dev libmagic file-dev libffi libffi-dev
      - apk add cmake gcc g++ make pkgconfig git boost-dev gd-dev libmad-dev libsndfile-dev libid3tag-dev wget postgresql-dev
      - pip install --upgrade pip setuptools
      - pip install --cache-dir=/cache flake8
      - pip install --cache-dir=/cache -r requirements.txt
      - python setup.py install
      - ./tests/install_audiowaveform.sh
      - flake8 .
      - python setup.py test

  rebuild-cache:
      image: drillster/drone-volume-cache
      rebuild: true
      mount:
          - .cache
      volumes:
          - /tmp/cache:/cache

  notify:
    image: plugins/slack
    channel: gitea
    secrets:
      - SLACK_WEBHOOK
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure, success ]

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=reel2bits_test
